# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bnRcTCsSsOovF1wVxWgZrElQXrnhku7U
"""

a = input("숫자를 입력해주세요:")
b = input("숫자를 입력해주세요:")
a_ = int(a)
b_ = int(b)
try:
  int(a) and int(b)
except:
  print("숫자를 입력해주세요.")
try :
  c = a_/b_
except:
  print("입력한 숫자를 확인해주세요.")
else:
  print(f'{a_}/{b_} = {c}')
finally:
  print("calculation completed")