# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwuTNJZWd-ypWYFPGD31glWCAyIH7K3J
"""
#소수 만들기
>itertools 도입
import itertools 
>solution함수 정의
>    >L은 소수의 개수, o는 소수 판별에 사용
def solution(*nums):
  L = 0
  combination_ = itertools.combinations(nums,3)
  list_ = []
  o = 0


>조건 판별
>     > 3~50개의 숫자 갯수 제한 설정
  if 3 <= len(nums) <= 50 :
    pass
  else :
    print("3개 이상 50개 이하로 입력해주십시오.")
  for i in nums :
    t = 0
    for j in nums :
     if j == i :
       t += 1
     if t > 1 :
      print("같은 숫자를 입력하지 마십시오.")


>    > 숫자 크기 제한 설정
    if 1<=i<=1000:
      pass
    else :
      print("1~1000사이의 숫자만 입력해 주십시오.")
>    > 뽑은 조합의 합 구하기 
  for combination in combination_:
    list_.append(sum(combination))


> 소수인지 아닌지 판별하기
  for element in list_ :
    o=0
    for s in range(2,element) :
     if  element % s == 0 :
      continue
     else :
      o += 1
    if o == element-2 :
      L += 1
  return L
