# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bnRcTCsSsOovF1wVxWgZrElQXrnhku7U
"""
#나눗셈 계산기
>숫자 입력
a = input("숫자를 입력해주세요:")
b = input("숫자를 입력해주세요:")

>정수변환
a_ = int(a)
b_ = int(b)
>a,b가 정수인지 시도하기
try:
  int(a) and int(b)
except:
  print("숫자를 입력해주세요.")
>a_/b_  시도하기
try :
  c = a_/b_
except:
  print("입력한 숫자를 확인해주세요.")
else:
  print(f'{a_}/{b_} = {c}')
>계산완료 출력하기
finally:
  print("calculation completed")
