# -*- coding: utf-8 -*-
"""실습과제2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfT__bxUSBEp3c7ylXC5j3uju5Z-NMKj
"""
#단어들의 길이 구하기 
>단어 리스트 
words = ["knowledge", "hardwork", "attitude"]
>    >길이 리스트로 변환하기
words = list(map(len,words))
>    >출력
words
#동전 던지기 게임
>랜덤 모듈 도입
import random
>    >함수 정의
def dongjeon(k) :
  adj = ['head','tail']
  s = random.choice(adj)
  if s == k :
    print('당신이 승리했습니다!')
  else :
    print('당신이 패배했습니다.')
>     >입력받기
k_ = str(input("head(앞면)과 tail(뒷면) 중 하나를 입력하십시오. : "))
dongjeon(k_)

#대문자는 소문자로,소문자는 대문자로 변환하기
>영어 문자열 입력받기
en = str(input("영어문자열을 입력하십시오 : "))
>    >영어 소문자 리스트에 속하는지 판별하고 있으면 대문자로 바꾸고 없으면 소문자로 변환 
eng = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
big= []
for i in range(0,len(en)) :
  if en[i] in eng :
    big.append(en(i).upper)
  else :
    big.append(en(i).lower)
print(big)
